---
deployment:
  tasks:
    - export DEPLOYPATH=/home//public_html/
    - /bin/cp/ index.html $DEPLOYPATH
    - /bin/cp/ about.html $DEPLOYPATH
    - /bin/cp/ services.html $DEPLOYPATH
    - /bin/cp/ styles.css $DEPLOYPATH
    - /bin/cp/ -R js $DEPLOYPATH
    - /bin/cp/ -R images $DEPLOYPATH